sudo: false
language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm-3.12

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm-3.12

install:
  - composer self-update

before_script:
  - composer install --no-interaction

script:
  - ./vendor/bin/phpunit
